 MODULE FPSM2D_DDATA
 !PURPOSE:
 !WRITE AND READ BINARY FILES CONTAINING THE
 !MODEL DESCRIPTION AND INITIAL CONDITIONS
 !TO BE LINKED WITH THE SIMULATION PROCEDURE
 !AND WITH THE DATA PREPARATION PROCEDURE
 !NO MPI CALLS CONTAINED - CAN BE LINKED WITH SCALAR DATA PREPARATION
    
    USE FPSM2D_FILEUNITS

	
	IMPLICIT NONE 
	
	INTEGER, PARAMETER, PUBLIC :: FPSM2D_DDATA_VP=1,&
	                              FPSM2D_DDATA_VS=2,&
								  FPSM2D_DDATA_RHO=3,&
								  FPSM2D_DDATA_OLD=4,&
								  FPSM2D_DDATA_NOW=6
	INTEGER, PARAMETER, PUBLIC :: FPSM2D_DDATA_N=7 !NUMBER OF DIFFERENT DATA
								  
								  !FNAMES OF INITIAL STATES!
								  	
    PRIVATE :: 	BUILDNAME

	CONTAINS
!=======================================
	
 SUBROUTINE FPSM2D_DDATA_LOAD(PLANE,IC,OK)
  REAL, DIMENSION(:,:), INTENT(OUT) :: PLANE
  INTEGER, INTENT(IN) :: IC
  LOGICAL, INTENT(OUT) :: OK
  !-----------------------------
  INTEGER :: IU
  CHARACTER(LEN=7) :: FNAME
  
   OK=.FALSE.
   FNAME=BUILDNAME(IC)
   IU=FPSM2D_FILEUNITS_DDATA+IC
   OPEN(IU,FILE=FNAME,FORM='UNFORMATTED',ACCESS='STREAM',STATUS='OLD',ERR=10)
   READ(IU,ERR=10) PLANE
   CLOSE(IU)
   OK=.TRUE.
   PRINT*, FNAME//' LOAD'
10 CONTINUE

 IF(.NOT.OK) PRINT*, 'ERROR IN READING FILE ',FNAME

	
 END SUBROUTINE FPSM2D_DDATA_LOAD
!=================================================

 SUBROUTINE FPSM2D_DDATA_SAVE(PLANE,IC,OK)
  REAL, DIMENSION(:,:), INTENT(IN) :: PLANE
  INTEGER, INTENT(IN) :: IC
  LOGICAL, INTENT(OUT) :: OK
  CHARACTER(LEN=7) :: FNAME
  INTEGER :: IU
  
   OK=.FALSE.
   FNAME=BUILDNAME(IC)
   IU=FPSM2D_FILEUNITS_DDATA+IC
   OPEN(IU,FILE=FNAME,FORM='UNFORMATTED',ACCESS='STREAM',ERR=20)
   WRITE(IU) PLANE
   CLOSE(IU)
   OK=.TRUE.
   PRINT*, FNAME//' SAVED'
20 CONTINUE

   IF(.NOT.OK) PRINT*, 'ERROR:'//FNAME//' NOT SAVED'
   
 END 
!=================================================

 CHARACTER(LEN=7) FUNCTION BUILDNAME(I)
  INTEGER :: I
  INTEGER :: IC
  
  IC=(I-1)*3
  BUILDNAME=TRIM(FPSM2D_FILEUNITS_DDATA_FNAME(IC+1:IC+3))//'.DAT'
 
 END FUNCTION BUILDNAME
!=================================================
	
 END MODULE FPSM2D_DDATA