 MODULE FPSM2D_FILEUNITS
  
   IMPLICIT NONE
	 
   INTEGER, PARAMETER :: FPSM2D_FILEUNITS_GENINPUT=20
   CHARACTER(LEN=*), PARAMETER:: FPSM2D_FILEUNITS_GENINPUT_FNAME='FPSM2D_INPUT.DAT'
   
   INTEGER, PARAMETER :: FPSM2D_FILEUNITS_DDATA=30
   CHARACTER(LEN=*), PARAMETER:: FPSM2D_FILEUNITS_DDATA_FNAME='VP VS RHOU1XU1YU2XU2Y'
   
   INTEGER, PARAMETER :: FPSM2D_FILEUNITS_OUTPUT=50
   CHARACTER(LEN=*), PARAMETER:: FPSM2D_FILEUNITS_OUTPUT_FNAME='FPSM2D_OUTPUT.DAT'
 
 END MODULE FPSM2D_FILEUNITS