 MODULE FPSM2D_GENINPUT
 
 USE FPSM2D_FILEUNITS
 
 IMPLICIT NONE
 
 INTEGER, PARAMETER, PUBLIC :: FPSM2D_GENINPUT_NINTEGERS=4
 INTEGER, PARAMETER, PUBLIC :: FPSM2D_GENINPUT_NREALS=3
 
 TYPE FPSM2D_GENINPUT_TYPE
  PRIVATE
  INTEGER, DIMENSION(FPSM2D_GENINPUT_NINTEGERS) :: IA
  REAL, DIMENSION(FPSM2D_GENINPUT_NREALS) :: RA
 END TYPE FPSM2D_GENINPUT_TYPE

 CONTAINS
 
 !==================================================
 
 SUBROUTINE FPSM2D_GENINPUT_LOAD(THIS,OK)
  TYPE(FPSM2D_GENINPUT_TYPE), INTENT(OUT) :: THIS
  LOGICAL, INTENT(OUT) :: OK
  
   OK=.FALSE.
  OPEN(FPSM2D_FILEUNITS_GENINPUT,FILE=FPSM2D_FILEUNITS_GENINPUT_FNAME,STATUS='OLD',ERR=10)
   
   READ(FPSM2D_FILEUNITS_GENINPUT,*,ERR=10) THIS%IA
   READ(FPSM2D_FILEUNITS_GENINPUT,*,ERR=10) THIS%RA
   OK=.TRUE.
  CLOSE(FPSM2D_FILEUNITS_GENINPUT)
 
   PRINT*, FPSM2D_FILEUNITS_GENINPUT_FNAME//' READ WITH'
   PRINT*, 'INTEGERS: '
   PRINT*, THIS%IA
   PRINT*, 'REALS: '
   PRINT*, THIS%RA
  
  RETURN
  
10 PRINT*, 'ERROR IN READING FILE ',FPSM2D_FILEUNITS_GENINPUT_FNAME
 
 END SUBROUTINE FPSM2D_GENINPUT_LOAD
 !==================================================
 
 SUBROUTINE FPSM2D_GENINPUT_GETNXNY(THIS,NX,NY)
  TYPE(FPSM2D_GENINPUT_TYPE), INTENT(IN) :: THIS
  INTEGER, INTENT(OUT) :: NX,NY
  
   NX=THIS%IA(1)
   NY=THIS%IA(2)
  
 END SUBROUTINE FPSM2D_GENINPUT_GETNXNY
 !==================================================
 
 SUBROUTINE FPSM2D_GENINPUT_GETNT(THIS,NT,NTRES)
  TYPE(FPSM2D_GENINPUT_TYPE), INTENT(IN) :: THIS
  INTEGER, INTENT(OUT) :: NT,NTRES
  
   NT=THIS%IA(3)
   NTRES=THIS%IA(4)
  
 END SUBROUTINE FPSM2D_GENINPUT_GETNT
 !================================================== 
 
 SUBROUTINE FPSM2D_GENINPUT_GETDDD(THIS,DDD)
  TYPE(FPSM2D_GENINPUT_TYPE), INTENT(IN) :: THIS
  REAL, DIMENSION(3), INTENT(OUT) :: DDD
  
  DDD=THIS%RA(1:3)
  
 END SUBROUTINE FPSM2D_GENINPUT_GETDDD
 !==================================================
 
 
 END MODULE FPSM2D_GENINPUT 