 MODULE FPSM2D_SIMULATION
!PURPOSE: PERFORM THE LOOP IN TIME OF A FPSM2D SIMULATION
!USAGE: INITIALIZE AN OBJECT OF TYPE "FPSM2D_SIMULATION_TYPE"
!WITH A CALL TO "FPSM2D_SIMULATION_NEW"
!PERFORM THE SIMULATION WITH "FPSM2D_SIMULATION_RUN"
!AT THE END DESTROY THE OBJECT WITH A CALL TO "FPSM2D_SIMULATION_KILL"

  USE FPSM2D_PINPUT
  USE FPSM2D_WAVE
 
  IMPLICIT NONE
  
  TYPE FPSM2D_SIMULATION_TYPE
	PRIVATE
	INTEGER :: NT,NTRES
	TYPE(FPSM2D_WAVE_TYPE) :: WAVE
  END TYPE FPSM2D_SIMULATION_TYPE
  
  CONTAINS
  
!=====================================================

  SUBROUTINE FPSM2D_SIMULATION_NEW(THIS,INPUT,OK)
	TYPE(FPSM2D_SIMULATION_TYPE), INTENT(INOUT) :: THIS
	TYPE(FPSM2D_PINPUT_TYPE), INTENT(IN) :: INPUT
	LOGICAL, INTENT(OUT) :: OK
	!------------------------------
	
   !EXTRACT DATA FROM INPUT USEFUL FOR SIMULATION LEVEL
	CALL FPSM2D_PINPUT_GETNT(INPUT,THIS%NT,THIS%NTRES)
	
  !INITIALIZE WAVE OBJECT
	CALL FPSM2D_WAVE_NEW(THIS%WAVE,INPUT,OK)
	
	IF(.NOT.OK) PRINT*, 'ERROR IN FPSM2D_SIMULATION_NEW' 
	
  END SUBROUTINE FPSM2D_SIMULATION_NEW
!=====================================================

  SUBROUTINE FPSM2D_SIMULATION_RUN(THIS)
	TYPE(FPSM2D_SIMULATION_TYPE), INTENT(INOUT) :: THIS
	!------------------------------
	INTEGER :: IT
	
	DO IT=1,THIS%NT
		CALL FPSM2D_WAVE_UPDATE(THIS%WAVE)
        IF(MOD(IT,THIS%NTRES).EQ.0) CALL FPSM2D_WAVE_OUTPUT(THIS%WAVE)
	ENDDO
	
  END SUBROUTINE FPSM2D_SIMULATION_RUN
!=====================================================

  SUBROUTINE FPSM2D_SIMULATION_KILL(THIS)
	TYPE(FPSM2D_SIMULATION_TYPE), INTENT(INOUT) :: THIS
	
	CALL FPSM2D_WAVE_KILL(THIS%WAVE)
	
  END SUBROUTINE FPSM2D_SIMULATION_KILL 
!=====================================================

 END MODULE FPSM2D_SIMULATION