 PROGRAM FPSM2D_MAIN
 
  USE FPSM2D_PINPUT
  USE FPSM2D_SIMULATION
	
	IMPLICIT NONE
  	
	LOGICAL :: OK
	INTEGER :: IERR
	TYPE(FPSM2D_PINPUT_TYPE) :: INPUT
	TYPE(FPSM2D_SIMULATION_TYPE) :: S
	
	!=====================================
	
	CALL MPI_INIT(IERR)
	OK=IERR.EQ.0
	
	IF(OK) CALL FPSM2D_PINPUT_NEW(INPUT,OK)
    IF(OK) CALL FPSM2D_SIMULATION_NEW(S,INPUT,OK)
	
    IF(OK) THEN
		CALL FPSM2D_SIMULATION_RUN(S)
		CALL FPSM2D_SIMULATION_KILL(S)	
	ENDIF
	
	CALL MPI_FINALIZE(IERR)
	
	STOP
	!=====================================
	
 END PROGRAM FPSM2D_MAIN